### ISSUE TITLE
WebXR: anti aliasing not enabled on XR session

### ISSUE THREAD

**Issue by Squareys** [Igalia/wolvic#111]
## Configuration

Wolvic version: 0.9.5
Wolvic build ID: ?

Hardware: Huawai 6dof

## Steps to Reproduce

1. Open https://constructarcade.com/game/avoid-the-dark/ or https://wonderlandengine.com/showcase/physics/
2. Start VR session by clicking the VR button
3. See crawling lines, especially easy to see on edges of yellow objects.

Wonderland Engine apps always have anti aliasing enabled, there is no way to turn it off for users.

**Comment by svillar** [comment]
Thanks for reporting. There is a Gecko setting to force MSAA. If I enable it then the aliasing is gone but at the cost of a very poor rendering performance.

I haven't debugged it yet in detail (too busy! :smile: ) but I guess that antialiasing is disabled in Gecko at some point in order to achieve a decent WebGL performance. I'll keep you posted.

**Comment by Squareys** [comment]
@svillar I don't think forcing it would be necessary, but those applications that have the luxury to enable it performance-wise should be allowed to :)

In this case, Wonderland Engine is explicitly requesting `antialias: true`, so I would expect it to be enabled on the WebXR framebuffer.

Usually performance in the browser/WebGL is bottlenecked by the CPU and MSAA only really affects GPU performance, so my hope is that you can enable it without too much performance loss (but a _huge_ gain in quality!).

**Comment by svillar** [comment]
I had time to debug the issue. Changing the MSAA samples in the settings does basically nothing. There are two reasons for that:

1. Gecko does not allow antialiasing unless a specific property is enabled.
2. The current Gecko VR code is using a property that was removed from the rest of the engine some time ago. That's why changing the msaa samples in wolvic wouldn't do anything even if we enable the property I mentioned in 1.

I already have patches for Wolvic and Gecko that fixes those two issues. I'll upload PRs for them soon. From early testing it looks like the Oculus Quest2 does great with MSAA 2x. However another hardware like the Huawei VR glasses do struggle a lot and should have it disabled by default.

**Comment by svillar** [comment]
JFTR [this](https://phabricator.services.mozilla.com/D146322) is the patch for Gecko.

**Comment by svillar** [comment]
Both Gecko and [Wolvic](https://github.com/Igalia/wolvic/pull/118) patches landed. Expect the fix to be included in the next release and thanks for reporting

**Comment by Squareys** [comment]
Awesome, thank you @svillar !
