### ISSUE TITLE
Can't play 8K video on meta quest 2.  4K plays normally.

### ISSUE THREAD

**Issue by kinng** [Igalia/wolvic#1283]
## Configuration

Wolvic version: latest version on Quest store
Wolvic build ID: 

 Meta Quest 2
Hardware: 

## Steps to Reproduce

1. Play this in 8K https://youtu.be/Bf5E2Gfvg-8?si=BQMqqrJqkgZh3b4E
2.
3.

## Current Behavior

 Image freezes and sound continues

## Expected Behavior
 It should play normally

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
I've checked on a desktop browser and the max allowed resolution is 4k. How do you get the 8k resolution?

**Comment by svillar** [comment]
Same behaviour in Meta browser. I guess you've been deceived by the title. The max resolution of that video is 4K. Please reopen if I missunderstood what you meant.

**Comment by kinng** [comment]
I do see 8K options and selectable too.  
![8K_2](https://github.com/Igalia/wolvic/assets/6156371/397e8574-8cf8-4c69-9af7-f8472d25be49)
![8K_1](https://github.com/Igalia/wolvic/assets/6156371/6ea246b0-58bd-4c85-a3f5-5502dcf402b1)

**Comment by javifernandez** [comment]
We have received similar reports via the feedback form:

 > regarding 360 video, high resolution > 4k won't play correctly, even on quest 3, only sound works and if you skip forward still frames are displayed example https://www.youtube.com/watch?v=YAABA-Ri0YI&amp;mozVideoProjection=360_auto&amp;app=desktop

**Comment by javifernandez** [comment]
I think we have a bug in the ```fxr_youtube``` extension we have to control how to request videos from the YouTube service. The JS code implements a [function](https://github.com/Igalia/wolvic/blob/fa7ed3939e00230fb5014a006872577eef42cac4/app/src/main/assets/extensions/fxr_youtube/main.js#L47) to override the video quality. However, this function is part of a more general one playerFixes() which is **only** called the first time the webpage with the video is loaded:

```
window.addEventListener("yt-update-title", () => {
    logDebug('page navigated and title updated');
    if (youtube.isWatchingPage()) {
        youtube.waitForVideoReady(() => youtube.playerFixes());
    }
});
```

If the user changes the video quality using the YT UI, the extension is not intercepting the action and it doesn't handle the new value. I believe that YT is using the new value selected by the user; this is very noticeable when selecting 8K quality, since the app hangs, the video freezes and only the music continue playing.

**Comment by svillar** [comment]
> I do see 8K options and selectable too. I am using fiber internet with actual download speed about 500 Mb/s. ![8K_1](https://private-user-images.githubusercontent.com/6156371/310300284-6ea246b0-58bd-4c85-a3f5-5502dcf402b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MDk5MTgsIm5iZiI6MTcxNDUwOTYxOCwicGF0aCI6Ii82MTU2MzcxLzMxMDMwMDI4NC02ZWEyNDZiMC01OGJkLTRjODUtYTNmNS01NTAyZGNmNDAyYjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MzBUMjA0MDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDFjMDQ4MDE4YzBjMjA3NmY3ZjhjNzgxOTRkZmYxNzQ3OGY5OGMwOTg1ZmM5Yjk1MWQxZTgzN2E1ZDY2NDBkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4BB9ihek2IWjbRz30Y8Vw16aSQQq8pMqg7n7Tdg_Ql8) ![8K_2](https://private-user-images.githubusercontent.com/6156371/310300278-397e8574-8cf8-4c69-9af7-f8472d25be49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MDk5MTgsIm5iZiI6MTcxNDUwOTYxOCwicGF0aCI6Ii82MTU2MzcxLzMxMDMwMDI3OC0zOTdlODU3NC04Y2Y4LTRjNjktOWFmNy1mODQ3MmQyNWJlNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MzBUMjA0MDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NThhMGZiZDQ2NGIwMzZiYjZiOWEyYzg2MzM2NTkwZGI3NzE0ZWY3MTUxNmNlMzY5YTMwNDViNDc5ZDdiZjI2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nw-vfzlWQqViF4uP4auLcKwh8F9Nb8GDxJiaDq7HQfI)

which browser is that? In which device?

**Comment by kinng** [comment]
Both Edge and Chrome browsers on Windows 11 desktop have the same 8k option.  Both are not smooth though, even with my 950Mbps fiber internet speed.  Looks like YouTube is the bottleneck but still it plays the whole video.  I am in the US.

**Comment by javifernandez** [comment]
I can choose 8K on Firefox desktop as well. 

![Screenshot from 2024-05-10 00-56-55](https://github.com/Igalia/wolvic/assets/2230241/39dfe0b6-08a7-4d2f-b498-06fbaa0e9434)

**Comment by javifernandez** [comment]
Although a video can be played in higher resolutions (8K in this case), YouTube may decide to offer lower values depending on many factors, like the device hw and software (codes and compression tools) capabilities or the device's screen size. 

As I commented before, among the qualities provided by YouTube Wolvic limit to 4K because the VR devices we target can't play them smoothly enough. However, users can choose higher qualities through the YouTube UI; if they are not offered is because YouTube decided to avoid them for that specific request.

**Comment by svillar** [comment]
I think this is a dup of #1196
