### ISSUE TITLE
App crashes when trying to a play video on any website with v0.9 Chromium release

### ISSUE THREAD

**Issue by sujay-digilens** [Igalia/wolvic#1414]
## Configuration

Wolvic version: release/chromium/0.9
Wolvic build ID: 
Gecko version: firefox-124.0.1
Active Build Variant: noapiArm64GeckoGenericDebug, Active ABI: arm64-v8a

Hardware: Digilens ARGO

## Steps to Reproduce

1. Play any video content on YouTube or any other website

## Current Behavior

Trying to play any video on the web crashes the app

## Context

I’m trying to build a version of the Wolvic XR Browser with the latest Chromium updates for our ARGO smart glasses platform.
1. I followed the developer workflow from (https://github.com/Igalia/wolvic/wiki/Developer-workflow#building-gecko) and built the wolvic project.
2. I was able to successfully build Gecko and add Gecko dependency to my android project.

## Error Logs and Stack Traces

<details open>
[logcat.txt](https://github.com/Igalia/wolvic/files/15240499/logcat.txt)

```
```

</details>

**Comment by svillar** [comment]
The developer workflow is for building Gecko not Chromium. AFAIK we haven't published any docs about how to build the Chromium port (we should! but we haven't had time). Also you mention that you're using Gecko 124. The current version of Wolvic is still using 121 so we cannot offer any stability promise with that newer version. Last but not least there is no trace of the crash so very little we could do with this report.

**Comment by sujay-digilens** [comment]
Got it. 

Let's say there's a prebuilt binary for the Chromium available, is there a way in the project to point to the Chromium build?

**Comment by svillar** [comment]
Yes you need to add  `chromium_aar=PATH_TO_DIR_WITH_CHROMIUM_AARS` to the `local.properties` file

**Comment by jdagdelen** [comment]
Any tips on how to build/where to find these AARs?

**Comment by svillar** [comment]
I'm going to close this because it has nothing to do with Chromium. The logcat shows a execution of Wolvic with Gecko using the NoAPI backend. That backend is meant for testing on regular phones, as the name suggests it does not use any VR SDK so it is not able to access controllers, it is not capable of hand tracking either, nor generating stereo views.

The problem seems to be in the codecs of the platform you're using. There is a lot of errors in `OMX-VDEC-1080P` component in the logs. Then at some point the VP9 decoder is selected `Found target decoder  OMX.qcom.video.decoder.vp9` but soon after that Wolvic dies. I suspect that your platform does not really support VP9 decoding. Please reopen if this analysis is incorrect and/or inaccurate.

**Comment by sujay-digilens** [comment]
Thanks for your analysis, Sergio.

I will look into that.


Sujay Nayak Anil
Software Engineer

***@***.***
