### ISSUE TITLE
Wolvic as default on Quest 3

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#1496]
**Is your feature request related to a problem? Please describe.**
Any request to load web content is managed by the Meta browser

**Describe the solution you'd like**
I'd like Wolvic to handle any web content related request by default 

**Describe alternatives you've considered**

**Additional context**

**Comment by svillar** [comment]
Wolvic does already declares itself as a browser app in Android since 1c9a4ec21. It can be selected as the default browser in those devices that allow you to select the default application. However AFAIK Meta does not provide the user an option in the UI to do that.

Maybe you can achieve that with `adb shell settings put secure browser_default_app com.igalia.wolvic` ?
