### ISSUE TITLE
XPI files can't seem to be installed. 

### ISSUE THREAD

**Issue by jake354** [Igalia/wolvic#1642]
## Configuration

Wolvic version: 1.7.1

Hardware: Meta Quest 3S

## Steps to Reproduce
I can't seem to install XPI files, despite enabling local addon installation in the developer settings. When I try to install an addon from downloads, the browser says "filetype not supported". I'm not sure if I'm just an idiot or what, but I can't for the life of me figure out how to make this work.  I'm slightly convinced it simply doesn't exist. 

```
```

</details>

**Comment by svillar** [comment]
I don't get the filetype not supported error, but I do get an error while trying to install an extension. The error is `java.lang.Exception: Unexpected error: [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFileInputStream.init]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: resource://gre/modules/addons/XPIInstall.sys.mjs :: getHashForFile :: line 64"  data: no]` meaning that it cannot access the file in the downloads location.

**Comment by svillar** [comment]
So the file permissions issue can be easily fixed by enabling storage permissions in Wolvic in the Privacy settings. We should likely be a bit more verbose and show a dialog to the user.

@jake354 regarding your specific issue, all the xpi's I downloaded from the official store can be read by Wolvic. Which one is giving you that error? I ask because your XPI seems to have the wrong MIME type

**Comment by svillar** [comment]
This is done now
