### ISSUE TITLE
PlatformActivity.java is in the wrong folder

### ISSUE THREAD

**Issue by Eklir** [Igalia/wolvic#195]
## Configuration

Wolvic version: 
Wolvic build ID: 

## Current Behavior
PlatformActivity.java is in the org.mozilla.vrbrowser folder, but it's package is com.igalia.wolvic, which shows error when open with  AS editor.  Why not fix it?

## Expected Behavior
PlatformActivity.java is in the com.igalia.wolvic folder

## Error Logs and Stack Traces

```
```

</details>

**Comment by svillar** [comment]
I don't know which platform you are taking a look at but for sure it isn't neither oculus nor hvr because both of them have the file in the proper place. If you're checking some other flavour then indeed it isn't migrated yet, but just because we are not maintaining them for the moment.

Thanks for reporting.

**Comment by Ana2k** [comment]
Started working on this.

**Comment by Eklir** [comment]
noapi flavor for me，picovr has the same issure

https://github.com/Igalia/wolvic/blob/main/app/src/noapi/java/org/mozilla/vrbrowser/PlatformActivity.java
https://github.com/Igalia/wolvic/tree/main/app/src/picovr/java/org/mozilla/vrbrowser

**Comment by svillar** [comment]
Recently fixed
