### ISSUE TITLE
softlocking quest when opening dll file in external app

### ISSUE THREAD

**Issue by catnotadog** [Igalia/wolvic#236]
## Configuration

Wolvic version: 42
Wolvic build ID: 

Hardware: quest 2

## Steps to Reproduce

1.download dll
2.open in external app

## Current Behavior

softlocking quest
## Expected Behavior

not softlocking
## Possible Solution

dont allow opening dll files, or only allow if it can be opened
## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Sorry this report does not provide much information about what's the issue. Could you be more specific?

**Comment by HollowMan6** [comment]
Nothing abnormal happens when opening dll files, let's close this issue.
![com igalia wolvic-20230927-205219](https://github.com/Igalia/wolvic/assets/43995067/7d5b2692-9a5d-47d3-9c8f-b45efbf687d0)
![com igalia wolvic-20230927-205233](https://github.com/Igalia/wolvic/assets/43995067/59c3d3a4-b46d-4a0a-b6df-999f5cf24ae3)
![com igalia wolvic-20230927-205341](https://github.com/Igalia/wolvic/assets/43995067/1f7668d8-6be5-4dec-a276-49453a6b0d92)
