### ISSUE TITLE
ASTC texture format not working in Meta Quest 2

### ISSUE THREAD

**Issue by mrjoshuaesmith** [Igalia/wolvic#252]
## Configuration

Wolvic version: 46
Wolvic build ID: 2974e751 (ac63.0.0)

Hardware: Meta Quest 2

## Steps to Reproduce

1. Visit this site: https://apps.kaonadn.net/5469657286836224/product.html#ap_22;:

## Current Behavior

On the Meta Quest 2 in Wolvic, the textures on the 3D model are black. The javascript console reports:
    WebGL warning: compressedTexImage: Bad `format`: Invalid enum value <enum 0x93b4>
(0x93b4 is ASTC format).
This same page works in the Quest Browser, so the hardware definitely supports this texture format.
The page works in Wolvic on the Quest 1 headset. This problem seems specific to the Quest 2 headset.
The test for ASTC format says the extension IS supported:
    gl.getExtension("WEBGL_compressed_texture_astc") != null

## Expected Behavior

The 3D model should be textured.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
Thanks for the very detailed report, we'll definitely check

**Comment by svillar** [comment]
After checking the code I can safely conclude that the problem is server side. Basically the server does not request the ASTC extension with the UA we send (I suspect it does it with any mobile UA). The same happens in desktop if you change the UA of your browser (there are extension for FF and Chrome) to the Wolvic's UA. See for example what my desktop FF renders with the Wolvic's UA.

![astc](https://user-images.githubusercontent.com/1826122/188170706-f3585b40-09cb-44b2-a7df-927c04738af5.png)


More in detail, web engines do not load WebGL extensions that are not requested. The JS code of that site is clearly wrong because it keeps trying to use the ASTC extension even if it has never requested it.

Do you have control over that website? I wouldn't like to have add an UA exception for it.

**Comment by mrjoshuaesmith** [comment]
You're totally right. There's a logic bug in our code that didn't request ASTC support when it found S3TC support. The Quest 1 apparently doesn't support S3TC, while the Quest 2 does. We'll fix it on our end. Thank you!
