### ISSUE TITLE
New Matrix channel?

### ISSUE THREAD

**Issue by msub2** [Igalia/wolvic#37]
Firefox Reality had its own Matrix channel at #fxr:mozilla.org. Will Igalia host a similar room for Wolvic?

**Comment by svillar** [comment]
Sorry for not replying before. I'm merging this with #198. We're indeed still in the process of defining our communications. This was not a priority at the beginning because all the work we had (have) to do is not very compatible with also taking care of synchronous communication channels as matrix.
