### ISSUE TITLE
[HandTracking] Hand rotations are not working perfectly

### ISSUE THREAD

**Issue by svillar** [Igalia/wolvic#421]
There are several issues with the rotation of the 3D models of the hands, like the ones reported [here](https://github.com/Igalia/wolvic/pull/410#issuecomment-1381554973) and [here](https://github.com/Igalia/wolvic/pull/410#issuecomment-1382073926).

Looks like the typical issues with the order of matrix multiplications

**Comment by Utopiah** [comment]
Hi, I'd like to test HandTracking in order to insure support for [my work](https://fabien.benetou.fr/pub/home/future_of_text_demo/engine/) (as it's mostly about hand tracking with physical keyboard) when the Lynx ships (hopefully soon).

Is it already on a release build? If not should I build one of elima's branches? Which devices are currently supported?

**Comment by svillar** [comment]
> Hi, I'd like to test HandTracking in order to insure support for [my work](https://fabien.benetou.fr/pub/home/future_of_text_demo/engine/) (as it's mostly about hand tracking with physical keyboard) when the Lynx ships (hopefully soon).
> 
> Is it already on a release build? If not should I build one of elima's branches? Which devices are currently supported?

It'll be shipped in the next version of Wolvic. The code is already in main, and it's OpenXR based, so any device supporting the basic hand tracking extensions should in theory work.

**Comment by svillar** [comment]
Let's close this as the patch landed

**Comment by svillar** [comment]
> Neat, is there any nightly apk for the Quest available?

Not yet, we're kind on a rush for the release. I promise it won't take much :smile:
