### ISSUE TITLE
visit https://www.mzgf.com/world webxr contents ,  an experience issue

### ISSUE THREAD

**Issue by dingsing2021** [Igalia/wolvic#548]
## Configuration

Wolvic version: 1.3.2
Wolvic build ID: 

Hardware: huawei vr glass 3dof&6dof

## Steps to Reproduce

1. visit [https://www.mzgf.com/world](url) and some webxr content, such as [https://vr.mzgf.com/?projectCode=00g1301M&projectType=ALL](url)
2.  here is an experience issues, the field of view is not in sync when the head rotates.
3.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by svillar** [comment]
I managed to load the page. It turns out that it's using WebVR which is a deprecated API not supported in Wolvic. Perhaps you could contact the administrators of the site and ask them to migrate to WebXR.

As you can see [here](https://caniuse.com/webvr) WebVR is either removed or deprecated in almost all major browsers

**Comment by dingsing2021** [comment]
it seem that this issue still there， please help to check it
