### ISSUE TITLE
Opciones salida en oculus quest 2

### ISSUE THREAD

**Issue by tolomeo1969** [Igalia/wolvic#626]
En principio crear opcion de salida del navegador al inicio de las oculus, con posibilidad de crear opción de minimizado y de ejecucion en segundo plano y de ayuda de manejo integrada.

**Comment by svillar** [comment]
Not sure I understand correctly what you're asking about. Try to open one issue for just one thing. So you mention several things:
1. Opening Wolvic when Meta device starts, as far as I know there is no "launch app at startup" setting in the system so that cannot be done on our side
2. Minimize app: Wolvic is by design an immersive app, so changing that to "standard" system app will involve a huge architectural change that is not going to happen at least in the short-medium term
3. Background execution: see previous point
4. Integrated Help: that's indeed something we lack. Specially now that we're adding hand tracking support and new actions with controller buttons, thanks for reminding us.

**Comment by tolomeo1969** [comment]
Buenas, quisiera saber si existe la idea de poner una salida al explirador wolvic en las oculus quest, de forma que se pueda salir de la aplicacion, de vuelta al sistema de las oculus, sin tener que reiniciar las oculus.

**Comment by tolomeo1969** [comment]
Buenas, quisiera saber si existe la idea de poner una salida al explirador wolvic en las oculus quest, de forma que se pueda salir de la aplicación, de vuelta al sistema de las oculus, sin tener que reiniciar las oculus.

**Comment by svillar** [comment]
> Buenas, quisiera saber si existe la idea de poner una salida al explirador wolvic en las oculus quest, de forma que se pueda salir de la aplicación, de vuelta al sistema de las oculus, sin tener que reiniciar las oculus.

Claro, pulsas el botón de menu en el controlador derecho y saldrá el menu del sistema como en cualquier otra app. Desde ahí se puede salir de la app.
