### ISSUE TITLE
Ability to play Youtube videos over 4K quality in both regular and VR180/360

### ISSUE THREAD

**Issue by ThatVRPerson** [Igalia/wolvic#64]
**Is your feature request related to a problem? Please describe.**
When trying to play videos that are over 4K video quality (5K, 8K, etc) the video barely moves but the audio works fine (800+MB speeds with Wifi-6) not sure if related to a problem as Firefox Reality was unable to do the same thing.

**Describe the solution you'd like**
Ability to playback Youtube videos with quality **over** 4K as either a flat video or VR180/360 for higher quality immersion like you can do on other devices.

**Describe alternatives you've considered**
Running at only 4K resolution.

**Additional context**
Search for any content on Youtube that has over 4K quality (5K, 6K, 8K, 12K, etc) and the video will be unable to play smoothly in regular format, VR180/360.

**Comment by elima** [comment]
An update from my own testing:

I can reproduce this issue but with video qualities lower than 4K.

I think it depends on whether the media playback does buffering or not, so the bandwidth you have available matter. If playback needs to pause to do buffering, then it doesn't automatically resume afterwards. If you manually pause and play the video again, then it plays for a few seconds then stops again for more buffering.

**Comment by svillar** [comment]
OK after quite some investigation I think I know what this issue is about. Even if you select a 2k, 4k... quality in the YouTube player, it might happen (specially the first time you play the video) that you get a low-res video. The reason is because Gecko does not always report good values for fullscreen window sizes. This means that we create a fullscreen window with lower resolution than the selected stream.

There is little we could do at the moment as the issue is in Gecko. Removing the high-priority tag for now.

**Comment by svillar** [comment]
So there are a couple of things here. Currently we're capping the maximum resolution to 4k because FirefoxReality removed 5k playback [some time ago](https://bugzilla.mozilla.org/show_bug.cgi?id=1634189) because there were some platforms not supporting it.

That said we could revert that change **but** I found [this](https://support.google.com/youtube/answer/6375112?co=GENIE.Platform%3DDesktop&oco=0), in particular

> Note: In 2022, we started removing support for playback at resolutions between 4K and 8K. For example, we may no longer support playback at 5K.

So as YouTube is not going to eventually allow that, there is no point in enabling it from our side.
