### ISSUE TITLE
Missing the "Share with other apps" option in the downloads lists

### ISSUE THREAD

**Issue by javifernandez** [Igalia/wolvic#928]
## Configuration

Wolvic version: 1.4.2
Wolvic build ID:  102

Hardware:  Oculus Quest2

## Steps to Reproduce

1. Download any file
2. Go to the Downloads list dialog 
3. Click on the "..." that appears when hovering an item of the list

## Current Behavior

A contextual menu appears with just 3 options (see actual.png picture) and the "Share with other apps" option is not there

![actual](https://github.com/Igalia/wolvic/assets/2230241/0098cfee-a5a8-44bd-97fc-7a24132db358)
 
## Expected Behavior

The contextual menu should shown the "Share with other apps" option (see expected.png picture)

![expected](https://github.com/Igalia/wolvic/assets/2230241/088f704a-7560-4848-b86b-5f307b1ad434)

## Context

This worked in 1.4.1 so it's clearly a regression.

**Comment by HollowMan6** [comment]
I think we can close this as invalid. This is not a regression. In 1.4.2, we don't need `Share with other apps` any more, as downloaded files will be already stored in the device's public Downloads folder so they are available outside of Wolvic. This change makes Wolvic more useful and convenient, as it now follows the expected behavior of a Web browser.
